src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategoryRepository::class)
 */
class Category
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToMany(targetEntity=Project::class, mappedBy="categories")
     */
    private $projects;

    public function __construct()
    {
        $this->projects = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Project[]
     */
    public function getProjects(): Collection
    {
        return $this->projects;
    }

    public function addProject(Project $project): self
    {
        if (!$this->projects->contains($project)) {
            $this->projects[] = $project;
            $project->addCategory($this);
        }

        return $this;
    }

    public function removeProject(Project $project): self
    {
        if($this->projects->contains($project)){
            $this->projects->removeElement($project);
            $project->removeCategory($this);
        }
        
        return $this;
    }
}

src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProjectRepository::class)
 */
class Project
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255)
     * 
     */
    private $Title;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=10)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url(
     *          dnsMessage = "The host '{{ value }}' could not be resolved."
     * )
     */
    private $Github;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url(
     *          dnsMessage = "The host '{{ value }}' could not be resolved."
     * )
     */
    private $Weblink;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="projects")
     */
    private $categories;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getGithub(): ?string
    {
        return $this->Github;
    }

    public function setGithub(string $Github): self
    {
        $this->Github = $Github;

        return $this;
    }

    public function getWeblink(): ?string
    {
        return $this->Weblink;
    }

    public function setWeblink(string $Weblink): self
    {
        $this->Weblink = $Weblink;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
           
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
        }

        return $this;
    }
}

src/Form/CategoryType.php
<?php

namespace App\Form;

use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description', CKEditorType::class)
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Category::class,
        ]);
    }
}

src/Controller/CategoryController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Repository\CategoryRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CategoryController extends AbstractController
{
    /**
     * @Route("/category", name="category")
     */
    public function index(CategoryRepository $repo): Response
    {
        $category = $repo ->findAll();
        return $this->render('category/index.html.twig', [
            'Categories' => $category,
        ]);
    }
/**
     * @Route("/onecategory/{id}", name="showbycategory")
     */
    public function showbycategory(Category $category)
    {
        return $this->render('category/show.html.twig', [
            'Category' => $category,
        ]);
    }

}

templates/category/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CategoryController!{% endblock %}

{% block body %}
<div class="row">
{% for category in Categories %}
    <div class="col-12 col-lg-4">
        <h2>{{category.name}}</h2>
        <p>{{category.description|raw}}</p>
        {% for project in category.projects %}
            <p>{{ project.title }}</p> 
        {% endfor %}
    </div>
{% endfor %}
</div>
{% endblock %}

templates/category/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes projets avec la technologie {{Category.name}}{% endblock %}

{% block body %}
<div class="row mt-5" style="flex-wrap:wrap ; flex-direction:column">
    <h1>Mes projets avec la technologie {{Category.name}}</h1>
    <div>
    <p>{{Category.description|raw}}</p>
    </div>
    <div class="row">
    {% for project in Category.projects %}
    <div class="col-12 col-lg-4">
        <div class="card text-white bg-secondary mb-3" style="max-width: 20rem;">
            <div class="card-header text-center">
                <a href="{{ path('project_show', {'id': project.id}) }}">
                    {{project.title|upper}}
                </a>
            </div>
            <div class="card-body" style="text-align:center">
                <img src={{asset('uploads/Images/' ~ project.image)}} class="img-fluid"
                    style="text-align:center; height:150px">
                <div class="mt-2">
                    <a href={{project.github}} target="blanck"><button type="button"
                            class="btn btn-primary">GitHub</button></a>
                    <a href={{project.weblink}} target="blanck"><button type="button"
                            class="btn btn-primary">Web</button></a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
</div>
{% endblock %}