src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProjectRepository::class)
 */
class Project
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255)
     * 
     */
    private $Title;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=10)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url(
     *          dnsMessage = "The host '{{ value }}' could not be resolved."
     * )
     */
    private $Github;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url(
     *          dnsMessage = "The host '{{ value }}' could not be resolved."
     * )
     */
    private $Weblink;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="projects")
     */
    private $categories;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getGithub(): ?string
    {
        return $this->Github;
    }

    public function setGithub(string $Github): self
    {
        $this->Github = $Github;

        return $this;
    }

    public function getWeblink(): ?string
    {
        return $this->Weblink;
    }

    public function setWeblink(string $Weblink): self
    {
        $this->Weblink = $Weblink;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
           
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
        }

        return $this;
    }
}

src/Form/ProjectType.php
<?php

namespace App\Form;

use App\Entity\Project;
use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Title')
            ->add('Description', CKEditorType::class)
            ->add('Image', FileType::class, [
                'label' => 'Image',

        // unmapped means that this field is not associated to any entity property
                'mapped' => false,

        // make it optional so you don't have to re-upload the PDF file
        // every time you edit the Product details
                'required' => false,

        // unmapped fields can't define their validation using annotations
        // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                        new File([
                            'maxSize' => '1024k',
                            'mimeTypes' => [
                            'image/png',
                            'image/jpg','image/jpeg','image/gif'
                                ],
                'mimeTypesMessage' => 'Merci d\'uploader un fichier image valide',
                        ])
                            ],
            ])
            ->add('Github', UrlType::class)
            ->add('Weblink', UrlType::class)
            ->add('categories', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => false
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Project::class,
        ]);
    }
}

src/Controller/ProjectController.php
<?php

namespace App\Controller;

use App\Entity\Project;
use App\Entity\Category;
use App\Form\ProjectType;
use App\Form\CategoryType;
use App\Repository\CategoryRepository;
use App\Repository\ProjectRepository;
use Symfony\Component\HttpFoundation\Request;
// use Doctrine\ORM\EntityManagerInterface;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

class ProjectController extends AbstractController
{
    /**
     * @Route("/CRUD/admin", name="admin")
     */
    public function admin()
    {
        $projects = $this->getDoctrine()->getRepository(Project::class)->findAll();
        $categories =$this->getDoctrine()->getRepository(Category::class)->findAll();

        return $this->render('project/admin.html.twig', [
            'projects' => $projects,
            'categories' => $categories
            ]);
    }

    /**
     * @Route("/project", name="project")
     */
    public function index(ProjectRepository $repo, CategoryRepository $repocategory): Response
    {
        $projects = $repo ->findAll();
        $categories=$repocategory ->findAll();
        return $this->render('project/index.html.twig', [
            'controller_name' => 'ProjectController',
            'projects' => $projects,
            'categories' => $categories
        ]);
    }
    /**
     * @Route("/CRUD/project/new", name="new_project")
     * @Route("/CRUD/project/{id}/edit", name="edit_project")
     */
    public  function form(Project $project = null , Request $request){
        
        if(!$project){
            $project = new Project();
        }
        else{

            $oldimage=$project->getImage();

        }
        $Manager = $this->getDoctrine()->getManager();

        $form=$this->createForm(ProjectType::class,$project);
                    
        $form ->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            if ($project->getImage() !== null) {
                
                $brochureFile=$form->get('Image')->getData();

                if ($brochureFile) {
                    $originalFilename = pathinfo($brochureFile->getClientOriginalName(), PATHINFO_FILENAME);
                         // this is needed to safely include the file name as part of the URL
                    $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                    $newFilename = $safeFilename.'-'.uniqid().'.'.$brochureFile->guessExtension();

                            // Move the file to the directory where brochures are stored
                    try {
                        $brochureFile->move(
                        $this->getParameter('Images_directory'),
                        $newFilename
                        );
                    } catch (FileException $e) {
                    return $this->redirectToRoute('admin');
                    }

                    // updates the 'brochureFilename' property to store the PDF file name
                    // instead of its contents
                    $project->setImage($newFilename);
                }
            }
            else{
                $project->setImage($oldimage);
            }


            $Manager->persist($project);
            $Manager->flush();

            return $this->redirectToRoute('admin');
        }
        
      
        return $this->render('project/create.html.twig', [
                'formProject' => $form->createView(),
                'editmode' => $project->getId()!==null

        ]);
    
    }
    
    /**
     * @Route("/project/{id}", name="project_show")
     */
    public function show(Project $project){
        
        return $this->render('project/show.html.twig', [
            'project'   =>  $project,
            ]);
    }
/**
 * @Route("/CRUD/project/remove/{id}", name="remove_project")
 */
 public function removeProject(Project $project): Response
 {
    $entityManager=$this->getDoctrine()->getManager();
    $entityManager->remove($project);
    $entityManager->flush();
    return $this->redirectToRoute('admin');
 }


    /**
     * @Route("/CRUD/category/new", name="new_category")
     * @Route("/CRUD/category/{id}/edit", name="edit_category")
     */
    public  function categoryform(Category $category = null , Request $request){
        
        if(!$category){
            $category = new Category();
        }
        $Manager = $this->getDoctrine()->getManager();

        $form=$this->createForm(CategoryType::class,$category);
                    
        $form ->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $Manager->persist($category);
            $Manager->flush();

            return $this->redirectToRoute('admin');
        }
        
      
        return $this->render('project/createcategory.html.twig', [
                'formcategory' => $form->createView(),
                'editmode' => $category->getId()!==null

        ]);
    
    }

/**
 * @Route("/CRUD/category/remove/{id}", name="remove_category")
 */
public function removeCategory(Category $category): Response
{
   $entityManager=$this->getDoctrine()->getManager();
   $entityManager->remove($category);
   $entityManager->flush();
   return $this->redirectToRoute('admin');
}

}

templates/project/admin.html.twig
{% extends 'base.html.twig' %}
{% block title %} Administration {% endblock %}
{% block body %}
<div>
    <div class="row mt-5">
        <div class="col-12">
            <a href="{{ path('new_project') }}" class="btn btn-primary " style="float: right">Ajouter</a>
            <h5>Projets</h5>
            <table>
                <thead>
                    <tr>
                        <th style="max-width:10%">#</th>
                        <th style="max-width:20%">Titre</th>
                        <th style="max-width:20%">Lien Image</th>
                        <th style="max-width:20%">Github</th>
                        <th style="max-width:20%">Lien URL</th>
                        <th style="max-width:10%">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% set i = 1 %}
                    {% for project in projects %}
                    <tr>
                        <td>{{ i }}</td>
                        <td><a href="{{ path('project_show', {'id': project.id}) }}"
                                target="_blank">{{ project.title }}</a></td>
                        <td>{{project.Image}}</td>
                        <td>{{project.Github}}</td>
                        <td>{{project.Weblink}}</td>
                        <td>
                            <a href="{{ path('edit_project', {'id': project.id}) }}"><i
                                    class="material-icons blue-text">edit</i></a>
                            <a href="{{ path('remove_project', {'id': project.id}) }}"><i
                                    class="material-icons red-text">delete</i></a>
                        </td>
                    </tr>
                    {% set i = i+1 %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-12">
            <a href="{{ path('new_category') }}" class="btn btn-primary " style="float: right">Ajouter</a>
            <h5>Catégories</h5>
            <table>
                <thead>
                    <tr>
                        <th style="max-width:10%">#</th>
                        <th style="max-width:20%">Nom</th>
                        <th style="max-width:60%">Description</th>
                        <th style="max-width:10%">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% set i = 1 %}
                    {% for category in categories %}
                    <tr>
                        <td>{{ i }}</td>
                        <td>{{ category.name }}</td>
                        <td>{{category.description|raw}}</td>
                        <td>
                            <a href="{{ path('edit_category', {'id': category.id}) }}"><i
                                    class="material-icons blue-text">edit</i></a>
                            <a href="{{ path('remove_category', {'id': category.id}) }}"><i
                                    class="material-icons red-text">delete</i></a>
                        </td>
                    </tr>
                    {% set i = i+1 %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

templates/project/create.html.twig
{% extends 'base.html.twig' %}
{% block title %} {% if editmode %}Mise à jour du Projet{% else %}Nouveau projet{% endif %} {% endblock %}
{% form_theme formProject 'bootstrap_4_layout.html.twig' %}
{% block body %}

<h1 class="mt-5">
{% if editmode %}
Modification du projet
{% else %}
Ajout d'un projet
{% endif %}
</h1>
{{ form_start(formProject)}}

{{ form_row(formProject.Title, {'attr': {
                            'placeholder': 'Titre du projet'
}})}}

{{ form_row(formProject.Description, {'attr': {
                            'placeholder': 'Description'
}})}}

{{ form_row(formProject.Image, {'attr': {
                            'placeholder': 'Image'
}})}}

{{ form_row(formProject.Github, {'attr': {
                            'placeholder': 'GitHub du projet'
}})}}

{{ form_row(formProject.Weblink, {'attr': {
                            'placeholder': 'Url du projet'
}})}}
<div>
{{ form_label(formProject.categories, 'Choisissez une ou plusieurs catégories') }}
{{ form_widget(formProject.categories) }}
</div>
<button type="submit" class="btn btn-primary mt-5">
{% if editmode %}
Enregistrer
{% else %}
Ajouter le projet
{% endif %}
</button>

{{ form_end(formProject)}}

{% endblock %}

templates/project/createcategory.html.twig
{% extends 'base.html.twig' %}
{% block title %} {% if editmode %}Mise à jour de la catégorie{% else %}Nouvelle catégorie{% endif %} {% endblock %}
{% form_theme formcategory 'bootstrap_4_layout.html.twig' %}
{% block body %}

<h1 class="mt-5">
{% if editmode %}
Modification de la catégorie
{% else %}
Ajout d'une catégorie
{% endif %}
</h1>
{{ form_start(formcategory)}}

{{ form_row(formcategory.name, {'attr': {
                            'placeholder': 'Nom de la catégorie'
}})}}

{{ form_row(formcategory.description, {'attr': {
                            'placeholder': 'Description'
}})}}

<button type="submit" class="btn btn-primary">
{% if editmode %}
Enregistrer
{% else %}
Ajouter la catégorie
{% endif %}
</button>

{{ form_end(formcategory)}}

{% endblock %}

templates/project/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes projets{% endblock %}

{% block body %}

<div class="row my-3 justify-content-center">
    <h1>Mes projets</h1>  
</div>
<h2> Filtrer par technologies</h2>
<div class="row my-3 justify-content-around">
{% for  category in categories %}
<a href="{{ path('showbycategory', {'id': category.id}) }}" target="blanck"><button type="button"
                            class="btn btn-primary">{{category.name}}</button></a>
{% endfor %}
</div>
<div class="row">
{% for project in projects %}
    <div class="col-12 col-lg-4">
        <div class="card text-white bg-secondary mb-3" style="max-width: 20rem;">
            <div class="card-header text-center">
            <a href="{{ path('project_show', {'id': project.id}) }}">
            {{project.title|upper}}
            </a>
            </div>
            <div class="card-body" style="text-align:center">
                <img src={{asset('uploads/Images/' ~ project.image)}} class="img-fluid" style="text-align:center; height:150px">
                {# <p class="card-text">{{project.description}}.</p> #}
                <div class="mt-2">
                <a href={{project.github}} target="blanck"><button type="button" class="btn btn-primary">GitHub</button></a>
                <a href={{project.weblink}} target="blanck"><button type="button" class="btn btn-primary">Web</button></a>
                </div>
            </div>
        </div>
    </div>
    
{% endfor %}
</div>


{% endblock %}

templates/project/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{project.title}}{% endblock %}

{% block body %}

<div class="row my-5 justify-content-center">
    <h1>{{project.title}}</h1>
</div>
<div class="row justify-content-center" style="flex-wrap:wrap ; flex-direction:column">

    <div style="width:100%;text-align:center">
    <img src={{ asset('uploads/Images/' ~ project.image)}} style="width:50%; height:auto">
    </div>
    <div>
    <p>{{project.description|raw }}</p>
    </div>
    <div style="width:100%;text-align:center">
    <a href={{project.github}} target="blanck"><button type="button" class="btn btn-primary">GitHub</button></a>
    <a href={{project.weblink}} target="blanck"><button type="button" class="btn btn-primary">Web</button></a>
    </div>
    <div class="mt-3">
    <p>Technologies : 
        {% for categorie in project.categories %}
            {{ categorie.name }} 
        {% endfor %}
    </p>
    </div>
</div>
</div>

{% endblock %}